# Generated by Django 3.2.15 on 2022-10-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='enr_r',
        ),
    ]
