# Generated by Django 3.2.15 on 2022-10-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_userdb_enr_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_l', models.CharField(max_length=20)),
                ('phone_l', models.IntegerField()),
                ('enroll_l', models.IntegerField()),
                ('email_l', models.CharField(max_length=20)),
                ('pwd_l', models.CharField(max_length=20)),
            ],
        ),
    ]
