# Generated by Django 3.2.15 on 2022-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_lawyerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerdb',
            name='law',
            field=models.CharField(default='Civil', max_length=20),
        ),
    ]
