# Generated by Django 3.2.15 on 2022-10-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_lawyerdb_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerdb',
            name='image',
            field=models.ImageField(default='null.jpg', upload_to='Image'),
        ),
        migrations.AlterField(
            model_name='lawyerdb',
            name='law',
            field=models.CharField(max_length=20),
        ),
    ]
