# Generated by Django 3.2.15 on 2022-10-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20221010_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=2000)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.userdb')),
            ],
        ),
    ]
