# Generated by Django 3.2.15 on 2022-10-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_bookdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='room',
            field=models.CharField(default='room1', max_length=20),
        ),
        migrations.AddField(
            model_name='bookdb',
            name='status',
            field=models.IntegerField(default='1'),
        ),
    ]
