# Generated by Django 3.2.15 on 2022-10-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20221012_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='status',
            field=models.IntegerField(default='0'),
        ),
    ]
