# Generated by Django 3.2.15 on 2022-10-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_alter_bookdb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='room',
            field=models.CharField(default='nul', max_length=20),
        ),
    ]
