# Generated by Django 3.2.15 on 2022-10-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_alter_bookdb_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='room',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
