# Generated by Django 3.2.15 on 2022-10-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_bookdb_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='reason',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
