# Generated by Django 3.2.15 on 2022-10-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_bookdb_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='status',
            field=models.CharField(default='accept', max_length=20),
        ),
    ]
