# Generated by Django 3.2.15 on 2022-10-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_bookdb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='status',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
