# Generated by Django 3.2.15 on 2022-10-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_auto_20221014_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='reason_r',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='userdb',
            name='status_r',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
