# Generated by Django 3.2.15 on 2022-10-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_auto_20221014_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_m', models.CharField(max_length=20)),
                ('email_m', models.CharField(max_length=20)),
                ('phone_m', models.IntegerField()),
                ('reason_m', models.CharField(max_length=100)),
                ('message_m', models.CharField(max_length=1000)),
            ],
        ),
    ]
